docs/api/remote-procedure-call-quick-reference.md
docs/api/remote-procedure-calls.md
docs/dashcore/wallet-arguments-and-commands.md
docs/examples/introduction.md
docs/guide/introduction.md
docs/index.md
docs/resources/glossary.md
index.md

Fix some navigation inconsistency. Make [main page](https://dash-docs--18.org.readthedocs.build/projects/core/en/18/index.html) more similar to docs.dash.org and also improve the [Core docs page](https://dash-docs--18.org.readthedocs.build/projects/core/en/18/docs/index.html).

docs: update main page info

---

docs/examples/p2p-network-parsing-a-merkleblock.md
docs/examples/transaction-tutorial-offline-signing.md
docs/guide/block-chain-block-chain-overview.md
docs/guide/block-chain-block-height-and-forking.md
docs/guide/block-chain-consensus-rule-changes.md
docs/guide/contracts-micropayment-channel.md
docs/guide/dash-features-masternode-sync.md
docs/guide/mining-pool-mining.md
docs/guide/mining-solo-mining.md
docs/guide/operating-modes-full-node.md
docs/guide/p2p-network-block-broadcasting.md
docs/guide/p2p-network-initial-block-download.md
docs/guide/transactions-p2pkh-script-validation.md
docs/guide/transactions-p2sh-scripts.md
docs/guide/transactions.md
docs/guide/wallets-wallet-files.md
docs/guide/wallets-wallet-programs.md
docs/reference/block-chain-block-headers.md
docs/reference/p2p-network-control-messages.md
docs/reference/p2p-network-data-messages.md
docs/reference/p2p-network-governance-messages.md
docs/reference/p2p-network-masternode-messages.md
docs/reference/p2p-network-privatesend-messages.md
docs/reference/transactions-opcodes.md
docs/reference/wallets.md

I realized shortly after merging #30 that we could just reference the images locally from the `img/*` directories :see_no_evil: This is much better since it doesn't depend on anything being present in `main` before being used elsewhere. And also the images will be located in the build output and won't be dependent on GitHub being online.
Preview build: https://dash-docs--31.org.readthedocs.build/projects/core/en/31/

refactor: switch to referencing images locally

---

docs/dashcore/wallet-arguments-and-commands-dash-cli.md

> View [the list of RPCs](../api/remote-procedure-call-quick-reference.md) for more detailed information.
'here' is nondescript, doesn't catch the reader's eye, and doesn't help the reader to find what they're looking for

Replace 'here' with descriptive text

---

docs/reference/p2p-network-control-messages.md

Includes v19.2 update to ChainLocks
Preview build: https://dash-docs--35.org.readthedocs.build/projects/core/en/35/

docs: spork updates

---

docs/guide/dash-features-proof-of-service.md

We messed up formatting here when working on meta. This corrects it.
Preview build: https://dash-docs--43.org.readthedocs.build/projects/core/en/43/

docs: correct formatting around eval-rst

---

docs/api/remote-procedure-calls.md

Updated based on input from [Discord](https://discord.com/channels/484546513507188745/495696706638184482/1122956155501690901) regarding the lack of info similar to https://en.bitcoin.it/wiki/API_reference_%28JSON-RPC%29#Multi-wallet_RPC_calls.
Preview build: https://dash-docs--48.org.readthedocs.build/projects/core/en/48/

docs: update multi-wallet RPC info

---

_static/css/pydata-overrides.css
_static/js/pydata-search-close.js
conf.py
requirements.txt

Replace pydata theme's built-in search with search as you type
Note: for an unknown reason, the PR build doesn't actually have functional search. It can be previewed on this build of the branch itself which does work and is presumably reflective of how it will actually work when merged: https://dash-user-docs.readthedocs.io/projects/core/en/v19-rtd-sphinx-search
https://dash-docs--50.org.readthedocs.build/projects/core/en/50/

feat: add readthedocs-sphinx-search

---

docs/api/remote-procedure-call-quick-reference.md
docs/api/remote-procedure-calls-wallet.md

Adds the `wipewallettxes` RPC added in 19.3
Preview build: https://dash-docs--56.org.readthedocs.build/projects/core/en/56/docs/api/remote-procedure-calls-wallet.html#wipewallettxes

docs(rpc): add wipewallettxes

---

docs/reference/p2p-network-control-messages.md
docs/reference/p2p-network-data-messages.md
docs/reference/transactions-special-transactions.md

Initial updates related to Dash Core v20 p2p updates. Does not include asset lock info.
Preview build: https://dash-docs--63.org.readthedocs.build/projects/core/en/63/

docs: v20 p2p updates, part 1

---

docs/api/remote-procedure-calls-evo.md

Changed from int to float where incorrect. Also updated some formatting
Preview build: https://dash-docs--65.org.readthedocs.build/projects/core/en/65/docs/api/remote-procedure-calls-evo.html#protx-list

docs: operatorReward type correction

---

README.md
_templates/sidebar-main.html
conf.py
docs/guide/dash-features.md
index.md

Switches links from readme.io to docs.dash.org
Preview build: https://dash-docs--68.org.readthedocs.build/projects/core/en/68/

feat: update platform docs links

---

docs/reference/transactions-special-transactions.md

Update the CbTx docs based on [DIP29](https://github.com/dashpay/dips/blob/master/dip-0029.md) and asset lock additions
Preview build: https://dash-docs--78.org.readthedocs.build/projects/core/en/78/

docs: v20 cbtx updates

---

docs/dashcore/wallet-arguments-and-commands-dash-cli.md
docs/dashcore/wallet-arguments-and-commands-dash-tx.md
docs/dashcore/wallet-arguments-and-commands-dash-wallet.md
docs/dashcore/wallet-arguments-and-commands-dashd.md

Updates the dashd, dash-cli, dash-qt, dash-tx, and dash-wallet info with v20.0.2
Preview build: https://dash-docs--85.org.readthedocs.build/projects/core/en/85/

docs: update dash core help

---

requirements.txt

To address this vulnerability: https://github.com/readthedocs/readthedocs.org/security/advisories/GHSA-qhqx-5j25-rv48

fix: bump to latest version of sphinx search

---

docs/reference/p2p-network-privatesend-messages.md

Removed some deprecated fields and updated examples
Preview build: https://dash-docs--93.org.readthedocs.build/projects/core/en/93/docs/reference/p2p-network-privatesend-messages.html#dsq

docs(p2p): update coinjoin messages

---

docs/reference/p2p-network-data-messages.md

`MSG_ISLOCK` is deprecated in Dash Core 20.1
Preview build: https://dash-docs--100.org.readthedocs.build/projects/core/en/100/

docs(p2p): islock deprecation

---

conf.py

Necessary due to RtD issue making the -dev branch the stable rtd selection

docs: link to latest instead of stable platform docs

---

docs/api/remote-procedure-calls-blockchain.md
docs/api/zmq.md
docs/examples/receiving-zmq-notifications.md
docs/guide/dash-features-instantsend.md
docs/guide/p2p-network-misbehaving-nodes.md
docs/reference/p2p-network-data-messages.md
docs/reference/p2p-network-deprecated-messages.md
docs/reference/p2p-network-instantsend-messages.md
docs/reference/p2p-network-quorum-messages.md

Updates InstantSend related docs based on islock deprecation in https://github.com/dashpay/dash/pull/5553.
Preview build: https://dash-docs--102.org.readthedocs.build/projects/core/en/102/docs/reference/p2p-network-deprecated-messages.html#islock

docs(p2p): islock deprecation, 2

---

docs/dashcore/wallet-arguments-and-commands-dash-cli.md
docs/dashcore/wallet-arguments-and-commands-dash-tx.md
docs/dashcore/wallet-arguments-and-commands-dash-wallet.md
docs/dashcore/wallet-arguments-and-commands-dashd.md

Preview build: https://dash-docs--104.org.readthedocs.build/projects/core/en/104/

docs(cli): update cli help docs

---

docs/api/remote-procedure-calls.md

Include "RPC" in the name for easier searching as suggested in #105
Preview build: https://dash-docs--106.org.readthedocs.build/projects/core/en/106/

chore: update rpc page name

---

docs/dashcore/wallet-arguments-and-commands-dash-cli.md
docs/dashcore/wallet-arguments-and-commands-dash-tx.md
docs/dashcore/wallet-arguments-and-commands-dash-wallet.md
docs/dashcore/wallet-arguments-and-commands-dashd.md
docs/dashcore/wallet-arguments-and-commands.md
docs/dashcore/wallet-configuration-file.md

Update to align with help output with latest v21
Preview build: https://dash-docs--110.org.readthedocs.build/projects/core/en/110/

docs: update core commands to v21

---

docs/api/remote-procedure-calls-raw-transactions.md
docs/reference/transactions-special-transactions.md

Preview build: https://dash-docs--112.org.readthedocs.build/projects/core/en/112/

docs: add asset lock special txs

---

docs/reference/p2p-network-protocol-versions.md

This was updated with v21.1
Preview build: https://dash-docs--113.org.readthedocs.build/projects/core/en/113/

chore: update p2p protocol version

---

docs/guide/dash-features-coinjoin.md
docs/reference/p2p-network-data-messages.md
docs/reference/p2p-network-privatesend-messages.md

DSQ will now be sent using inventory system (https://github.com/dashpay/dash/pull/6148). Update the p2p page and coinjoin details.
Preview build: https://dash-docs--121.org.readthedocs.build/projects/core/en/121/docs/guide/dash-features-coinjoin.html

docs(p2p): dsq updates

---

docs/api/remote-procedure-call-quick-reference.md
docs/api/remote-procedure-calls-dash.md
docs/api/remote-procedure-calls-evo.md
docs/api/remote-procedure-calls-network.md
docs/api/remote-procedure-calls-removed.md
docs/api/remote-procedure-calls-wallet.md

Preview build: https://dash-docs--123.org.readthedocs.build/projects/core/en/123/

docs(rpc): v22 rpc updates, 2

---

docs/reference/p2p-network-control-messages.md
docs/reference/p2p-network-protocol-versions.md

Preview build: https://dash-docs--124.org.readthedocs.build/projects/core/en/124/

docs: update protocol version table

---

docs/guide/dash-features-chainlocks.md
docs/guide/dash-features-coinjoin.md
docs/index.md

Preview build: https://dash-docs--128.org.readthedocs.build/projects/core/en/128/

chore: update insight links
