dashpay/docs-core

conf.py
docs/examples/receiving-zmq-notifications.md

Uses [sphinx-design tabbed code](https://sphinx-design.readthedocs.io/en/latest/tabs.html#tabbed-code-examples) feature with myst-parser.

feat: multitab code block

---

conf.py
index.md
requirements.txt

Add intersphinx config for user docs and use on the main page

build: add extensions and use intersphinx

---

docs/api/remote-procedure-calls-blockchain.md
docs/api/remote-procedure-calls-dash.md
docs/api/remote-procedure-calls-raw-transactions.md
docs/api/remote-procedure-calls-wallet.md
docs/api/remote-procedure-calls.md
docs/dashcore/wallet-arguments-and-commands-dash-cli.md
docs/dashcore/wallet-arguments-and-commands-dash-qt.md
docs/dashcore/wallet-arguments-and-commands-dash-tx.md
docs/dashcore/wallet-arguments-and-commands-dash-wallet.md
docs/dashcore/wallet-arguments-and-commands-dashd.md
docs/examples/testing-applications.md

https://dash-docs--20.org.readthedocs.build/projects/core/en/20/

feat: add references needed by user docs

---

requirements.txt

Update to current versions of most dependencies.
Preview: https://dash-docs--23.org.readthedocs.build/projects/core/en/23/

build: update dependencies

---

docs/api/remote-procedure-calls-blockchain.md

Preview build: https://dash-docs--26.org.readthedocs.build/projects/core/en/26/

chore: clarify InstantSend terminology

---

docs/dashcore/wallet-arguments-and-commands-dash-cli.md
docs/dashcore/wallet-arguments-and-commands-dash-qt.md
docs/dashcore/wallet-arguments-and-commands-dash-tx.md
docs/dashcore/wallet-arguments-and-commands-dash-wallet.md
docs/dashcore/wallet-arguments-and-commands-dashd.md
docs/dashcore/wallet-arguments-and-commands.md
docs/dashcore/wallet-configuration-file.md

Preview build: https://dash-docs--42.org.readthedocs.build/projects/core/en/42/

updated last meta

---

docs/api/remote-procedure-calls-address-index.md

Preview build: https://dash-docs--45.org.readthedocs.build/projects/core/en/45/

Removed mentions of "requiring wallet support"

---

docs/reference/p2p-network-governance-messages.md
docs/reference/p2p-network.md
docs/reference/transactions-opcodes.md

Preview build: https://dash-docs--46.org.readthedocs.build/projects/core/en/46/

some of the asides fixed

---

docs/reference/transactions-special-transactions.md

Moved during DIP repo refactor (dashpay/dips#137 <- Don't merge until that is merged)
Preview build: https://dash-docs--51.org.readthedocs.build/projects/core/en/51/

docs: update link to special txs file

---

docs/api/remote-procedure-calls-blockchain.md

Preview build: https://dash-docs--55.org.readthedocs.build/projects/core/en/55/

docs(rpc): add some labels for use in dashpay/docs

---

.readthedocs.yml
conf.py
docs/dips/README.md
docs/index.md
scripts/dip-format.sh

Pulls the dashpay/dips repo during builds and creates pages for all the DIPs.
Preview build: https://dash-docs--59.org.readthedocs.build/projects/core/en/59/docs/dips/README.html

feat: add dips to the resources section

---

docs/api/remote-procedure-calls-evo.md

Rename *_hpmn to *_evo 
Preview build: https://dash-docs--71.org.readthedocs.build/projects/core/en/71/

docs(rpc): update evonode protx docs

---

docs/api/remote-procedure-call-quick-reference.md
docs/api/remote-procedure-calls-network.md

Preview build: https://dash-docs--74.org.readthedocs.build/projects/core/en/74/

docs(rpc): add addpeeraddress rpc

---

docs/reference/block-chain-serialized-blocks.md

Preview build: https://dash-docs--75.org.readthedocs.build/projects/core/en/75/

docs: v20 block subsidy reward change

---

docs/api/remote-procedure-calls-evo.md

Add a current working example
Preview build: https://dash-docs--76.org.readthedocs.build/projects/core/en/76/

docs(rpc): update verifyislock example

---

docs/reference/transactions-special-transactions.md

Preview build: https://dash-docs--64.org.readthedocs.build/projects/core/en/64/docs/reference/transactions-special-transactions.html#mnhftx

docs: v20 p2p update for ehf

---

docs/api/remote-procedure-calls-blockchain.md

Preview build: https://dash-docs--77.org.readthedocs.build/projects/core/en/77/

docs(rpc): getblockchaininfo update

---

docs/reference/block-chain-serialized-blocks.md
docs/reference/p2p-network-control-messages.md
docs/resources/glossary.md

Updates some info now that the v20 hard fork has happened.
Preview build: https://dash-docs--83.org.readthedocs.build/projects/core/en/83/

docs: clarify block reward allocation

---

docs/reference/p2p-network-data-messages.md
docs/reference/transactions-special-transactions.md

Preview build: https://dash-docs--84.org.readthedocs.build/projects/core/en/84/

chore(reference): p2p updates

---

docs/reference/p2p-network-protocol-versions.md

Preview build: https://dash-docs--89.org.readthedocs.build/projects/core/en/89/

docs: update protocol version for v20

---

docs/reference/p2p-network-quorum-messages.md

Add an example v3/v4 qfcommit. Remove v1/v2 examples.
https://dash-docs--94.org.readthedocs.build/projects/core/en/94/docs/reference/p2p-network-quorum-messages.html#qfcommit

docs: qfcommit update

---

docs/api/remote-procedure-call-quick-reference.md
docs/api/remote-procedure-calls-evo.md

Preview build: https://dash-docs--96.org.readthedocs.build/projects/core/en/96/

docs(rpc): add quorum dkginfo

---

docs/api/remote-procedure-calls-evo.md

Thanks to @pshenmic for reporting
Preview build: https://dash-docs--114.org.readthedocs.build/projects/core/en/114/

chore: correct protx revoke params

---

docs/reference/transactions-special-transactions.md

Preview build: https://dash-docs--116.org.readthedocs.build/projects/core/en/116/

docs: update mnhftx with example

---

docs/api/remote-procedure-calls-dash.md
docs/guide/dash-features-instantsend.md
docs/reference/p2p-network-control-messages.md
docs/resources/glossary.md

Preview build: https://dash-docs--117.org.readthedocs.build/projects/core/en/117/docs/reference/p2p-network-control-messages.html#spork

docs: update spork info based on v21 mainnet hardening

---

docs/api/remote-procedure-calls-control.md
docs/api/remote-procedure-calls-evo.md
docs/dashcore/wallet-arguments-and-commands-dashd.md
docs/guide/dash-features-masternode-quorums.md

Preview build: https://dash-docs--119.org.readthedocs.build/projects/core/en/119/

docs: misc updates from v21.1

---

README.md

Preview build: https://dash-docs--126.org.readthedocs.build/projects/core/en/126/

docs: add note about migration to the readme
